#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "quad.h"
#include "ast.h"
#include "utils.h"
#include "codegen.h"

// The AST root generated by the parser
extern Program* ast_root;
extern int yyparse();
extern FILE* yyin;

#define STUDENT_NAME "Oren Palei"

int main(int argc, char* argv[]) {
    fprintf(stderr, "[DEBUG] Starting compiler execution...\n");

    if (argc < 2) {
        fprintf(stderr, "Usage: %s <source_file>\n", argv[0]);
        return 1;
    }

    const char* filepath = argv[1];
    fprintf(stderr, "[DEBUG] Attempting to open source file: %s\n", filepath);

    FILE* file = fopen(filepath, "r");
    if (!file) {
        fprintf(stderr, "[ERROR] Failed to open source file: %s\n", filepath);
        return 1;
    }

    // Set lexer input
    yyin = file;

    fprintf(stderr, "[DEBUG] Starting parsing via yyparse()\n");
    if (yyparse() != 0 || ast_root == NULL) {
        fprintf(stderr, "[ERROR] Parsing failed. Aborting.\n");
        fclose(file);
        return 1;
    }
    fclose(file);
    fprintf(stderr, "[DEBUG] Parsing completed successfully. AST built.\n");

    fprintf(stderr, "[DEBUG] Starting semantic analysis and quad generation...\n");
    if (!handle_program(ast_root)) {
        fprintf(stderr, "[ERROR] Semantic analysis failed. Aborting.\n");
        return 1;
    }
    fprintf(stderr, "[DEBUG] Semantic analysis and quad generation completed.\n");

    // Generate output filename
    char output_path[512];
    char* dot = strrchr(filepath, '.');
    if (dot) {
        snprintf(output_path, sizeof(output_path), "%.*s.quad", (int)(dot - filepath), filepath);
    } else {
        snprintf(output_path, sizeof(output_path), "%s.quad", filepath);
    }

    fprintf(stderr, "[DEBUG] Writing quads to output file: %s\n", output_path);
    if (!write_quads_to_file(output_path, quad_list)) {
        fprintf(stderr, "[ERROR] Failed to write output file: %s\n", output_path);
        return 1;
    }

    fprintf(stderr, "[DEBUG] Output file written successfully: %s\n", output_path);
    fprintf(stderr, "[INFO] Compilation completed by %s\n", STUDENT_NAME);
    return 0;
}
